# Generated by Django 4.1.4 on 2024-05-06 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games_app', '0009_alter_game_created_at_alter_game_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divisions_app', '0008_alter_division_created_at_alter_division_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_division', to='divisions_app.division')),
                ('desired_division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_division', to='divisions_app.division')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_app.game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosting_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
